# Generated by Django 2.2.7 on 2019-11-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ksiegarnia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ksiegarnia.Book')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ksiegarnia.Customer')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ksiegarnia.Employee')),
            ],
        ),
    ]
