# Generated by Django 2.2.7 on 2019-12-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ksiegarnia', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
